### ISSUE TITLE
Dunstrc?

### ISSUE THREAD

**Issue by fr3fou** [GabrielTenma/dotfiles#2]
It looks pretty sick :o mind if you upload it?

**Comment by GabrielTenma** [comment]
dunstrc? what is that?

**Comment by fr3fou** [comment]
Do you use dunst for notifications? Can I have the config file for it?

**Comment by GabrielTenma** [comment]
no
use command to show notify
notify-send "title" "description" --icon='/file/icon/location/icon.png/jpg'

**Comment by fr3fou** [comment]
what notification daemon do you use

**Comment by fr3fou** [comment]
https://wiki.archlinux.org/index.php/Desktop_notifications

**Comment by GabrielTenma** [comment]
xfce4-notifyd

**Comment by fr3fou** [comment]
oh I see, can you upload the theme / css / config for it?

**Comment by GabrielTenma** [comment]
theme notify : [Here](https://github.com/GabrielTenma/my-favorite-theme)
xfce notify without config

**Comment by fr3fou** [comment]
thenk u uwu
